# Generated by Django 3.1.7 on 2021-04-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='sms_order_phone_eaa29c_idx'),
        ),
    ]
